### ISSUE TITLE
軸の方向を教えてください

### ISSUE THREAD

**Issue by fenrir-naru** [istellartech/OpenMOMO#1]
加速度計/ジャイロについて、X/Y/Z軸の方向を教えてください。また座標系は右手系でしょうか。

**Comment by ina111** [comment]
座標系は右手系で、リフトオフ前のEast/North/Upに対して機体座標系（加速度・ジャイロセンサの軸方向：センサ座標系と一致させています）を合わせています。
![default](https://user-images.githubusercontent.com/1742472/30041518-b41afe50-9225-11e7-82e9-20bc1f312eb2.png)

射点座標系と機体座標系およびセンサ座標系の誤差精度についての情報もありますので、必要でしたらおっしゃってください。

**Comment by fenrir-naru** [comment]
ありがとうございます。誤差精度についても開示できるようでしたら、お願いいたします。
